# Notebook for drafting visualizations code for charts.py

In [4]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib as plt
import seaborn as sns
import plotly.express as px
import openpyxl

# For Qualitative Impact tab

In [15]:
# read in dataframes
df_admin = pd.read_csv('../notebooks/admin_clean_full.csv')
df_faculty = pd.read_csv('../notebooks/faculty_clean_full.csv')
df_student = pd.read_csv('../notebooks/student_clean_full.csv')

In [17]:
df_admin_quant = pd.read_csv('../notebooks/admin_quant.csv')
df_faculty_quant = pd.read_csv('../notebooks/faculty_quant.csv')
df_student_quant = pd.read_csv('../notebooks/student_quant.csv')

In [12]:
display(df_admin)

,StartDate,EndDate,Status,progress_pct,duration_seconds,Finished,recorded_date,response_id,consent,library_engagement,...,dashboard_use_nps_score,QID21,Q22,prefix,name,Q_RecaptchaStatus,data_support_effectiveness_num,dashboard_use_nps_group_calc,duration_minutes,survey_month
0,2026-02-20 16:22:26,2026-02-20 16:22:32,1,100,6,1,2026-02-20 16:22:33,R_7NB8iQGMqpurpEl,2,NaN,...,NaN,NaN,NaN,NaN,NaN,complete,NaN,NaN,0.1,2026-02
1,2026-02-21 18:50:18,2026-02-21 18:51:38,0,100,80,1,2026-02-21 18:51:39,R_2CVYEiXuSLK5ukN,1,2.0,...,5.0,NaN,NaN,NaN,NaN,complete,NaN,Detractor,1.3,2026-02
2,2026-02-26 11:08:00,2026-02-26 11:11:45,0,100,225,1,2026-02-26 11:11:46,R_2SuGE4XCiznIu2E,1,1.0,...,NaN,NaN,NaN,NaN,NaN,complete,NaN,NaN,3.8,2026-02
3,2026-02-26 13:07:30,2026-02-26 15:07:30,0,100,7200,1,2026-02-26 15:07:31,R_3GDhA9IlNZ6S9kd,1,NaN,...,NaN,NaN,NaN,NaN,NaN,complete,NaN,NaN,120.0,2026-02
4,2026-02-27 14:34:26,2026-02-27 14:34:31,1,100,4,1,2026-02-27 14:34:31,R_1IWXwAYrqdyfCLg,2,NaN,...,NaN,NaN,NaN,NaN,NaN,complete,NaN,NaN,0.1,2026-02
5,2026-02-27 15:30:51,2026-02-27 15:32:40,1,100,108,1,2026-02-27 15:32:40,R_7OMeQdljrxdRfRT,1,2.0,...,NaN,NaN,NaN,NaN,NaN,complete,NaN,NaN,1.8,2026-02
6,2026-02-28 18:08:51,2026-02-28 19:21:12,1,100,4340,1,2026-02-28 19:21:12,R_22mNPR1kkhssF69,1,4.0,...,NaN,NaN,2.0,asdfdsaf,asdfdsfsd,complete,NaN,NaN,72.3,2026-02
7,2026-03-01 19:58:26,2026-03-01 20:15:57,0,100,1050,1,2026-03-01 20:15:58,R_22AdjyFrQIsnyMs,1,4.0,...,10.0,Evidence that people put high value in the lib...,NaN,NaN,NaN,complete,NaN,Promoter,17.5,2026-03
8,2026-03-03 13:18:49,2026-03-03 13:26:28,0,100,459,1,2026-03-03 13:26:29,R_1kSUbuAohDJ1LHf,1,4.0,...,6.0,NaN,NaN,NaN,NaN,complete,NaN,Detractor,7.6,2026-03
9,2026-03-06 17:39:06,2026-03-06 17:42:55,0,100,229,1,2026-03-06 17:42:56,R_3Gd0CVhnhPT4Qnp,1,2.0,...,4.0,NaN,2.0,NaN,NaN,complete,NaN,Detractor,3.8,2026-03
10,2026-03-09 09:07:21,2026-03-09 09:08:37,0,100,76,1,2026-03-09 09:08:39,R_2zO6jSbNXDjZntx,1,2.0,...,0.0,NaN,NaN,NaN,NaN,complete,NaN,Detractor,1.3,2026-03

In [69]:
df_admin.describe()

,Status,progress_pct,duration_seconds,Finished,consent,library_engagement,essential_service,data_support_effectiveness,workflow_collaboration_story,dashboard_use_nps_group,dashboard_use_nps_score,Q22,data_support_effectiveness_num,duration_minutes
count,11.000000,11.0,11.000000,11.0,11.000000,8.000000,7.000000,6.000000,4.00000,5.000000,5.000000,2.0,0.0,11.000000
mean,0.363636,100.0,1252.454545,1.0,1.181818,2.625000,3.000000,3.333333,4.50000,1.400000,5.000000,2.0,NaN,20.872727
std,0.504525,0.0,2342.235529,0.0,0.404520,1.187735,2.645751,1.032796,0.57735,0.894427,3.605551,0.0,NaN,39.031323
min,0.000000,100.0,4.000000,1.0,1.000000,1.000000,1.000000,2.000000,4.00000,1.000000,0.000000,2.0,NaN,0.100000
25%,0.000000,100.0,78.000000,1.0,1.000000,2.000000,1.000000,3.000000,4.00000,1.000000,4.000000,2.0,NaN,1.300000
50%,0.000000,100.0,225.000000,1.0,1.000000,2.000000,1.000000,3.000000,4.50000,1.000000,5.000000,2.0,NaN,3.800000
75%,1.000000,100.0,754.500000,1.0,1.000000,4.000000,5.000000,3.750000,5.00000,1.000000,6.000000,2.0,NaN,12.550000
max,1.000000,100.0,7200.000000,1.0,2.000000,4.000000,7.000000,5.000000,5.00000,3.000000,10.000000,2.0,NaN,120.000000

In [13]:
display(df_faculty)

,StartDate,EndDate,Status,progress_pct,duration_seconds,Finished,recorded_date,response_id,consent,collection_support_rating,...,degree_program,status_or_role,Q_RecaptchaStatus,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,library_partner_nps_group_calc,duration_minutes,survey_month
0,2026-02-20 15:17:47,2026-02-20 15:17:51,1,100,4,1,2026-02-20 15:17:52,R_5lGkqSzjL3CkH9c,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,2026-02
1,2026-02-20 15:31:39,2026-02-20 15:31:45,1,100,5,1,2026-02-20 15:31:45,R_5G9UYPMekeOE28r,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,2026-02
2,2026-02-20 15:33:26,2026-02-20 15:34:05,1,100,38,1,2026-02-20 15:34:05,R_5ew54xzON4DfJLQ,1,4.0,...,1.0,4.0,NaN,NaN,NaN,NaN,NaN,Promoter,0.6,2026-02
3,2026-02-21 18:39:05,2026-02-21 18:45:48,0,100,402,1,2026-02-21 18:45:49,R_7phTOharDJGIM3A,1,3.0,...,NaN,NaN,complete,NaN,NaN,NaN,NaN,Detractor,6.7,2026-02
4,2026-02-26 11:13:30,2026-02-26 11:15:33,0,100,123,1,2026-02-26 11:15:34,R_3D7jElyEi0f50hH,1,NaN,...,NaN,NaN,complete,NaN,NaN,NaN,NaN,NaN,2.0,2026-02
5,2026-02-26 12:27:36,2026-02-26 12:52:37,0,100,1501,1,2026-02-26 12:52:38,R_6LU4Iu4T8Rq6bEV,1,NaN,...,NaN,NaN,complete,NaN,NaN,NaN,NaN,NaN,25.0,2026-02
6,2026-02-28 16:45:10,2026-02-28 17:59:48,0,100,4477,1,2026-02-28 17:59:49,R_5RggZEy7HtEWukM,1,3.0,...,NaN,NaN,complete,NaN,NaN,NaN,NaN,Detractor,74.6,2026-02
7,2026-03-01 09:04:38,2026-03-01 09:10:50,0,100,372,1,2026-03-01 09:10:52,R_69oeSM7dkgy6b9v,1,3.0,...,4.0,1.0,complete,NaN,NaN,NaN,NaN,Detractor,6.2,2026-03
8,2026-03-01 22:01:39,2026-03-01 22:05:45,0,100,245,1,2026-03-01 22:05:46,R_637Qbsb0u5g17xV,1,2.0,...,1.0,1.0,complete,NaN,NaN,NaN,NaN,Promoter,4.1,2026-03
9,2026-03-03 09:54:15,2026-03-03 09:58:46,0,100,271,1,2026-03-03 09:58:47,R_7Igb9R23L5Ie9Ct,1,2.0,...,2.0,1.0,complete,NaN,NaN,NaN,NaN,Detractor,4.5,2026-03
10,2026-03-06 16:19:15,2026-03-06 17:57:35,0,100,5900,1,2026-03-06 17:57:36,R_52ScowzZCJnGDvO,1,2.0,...,4.0,1.0,complete,NaN,NaN,NaN,NaN,Detractor,98.3,2026-03

In [16]:
display(df_student)

,StartDate,EndDate,Status,progress_pct,duration_seconds,Finished,recorded_date,response_id,consent,library_engagement,...,name,degree_program,.16,Q_RecaptchaStatus,Q_RecaptchaError,health_info_confidence_num,course_materials_satisfaction_num,library_nps_group_calc,duration_minutes,survey_month
0,2026-02-20 10:31:07,2026-02-20 10:32:19,1,100,72,1,2026-02-20 10:32:20,R_2Bs8DO1qWsQr8XE,1.0,4.0,...,NaN,NaN,NaN,error,executionFailed,NaN,NaN,Promoter,1.2,2026-02
1,2026-02-20 10:36:09,2026-02-20 10:36:13,1,100,3,1,2026-02-20 10:36:14,R_2fwDNWPIGlKfGJI,2.0,NaN,...,NaN,NaN,NaN,error,executionFailed,NaN,NaN,NaN,0.0,2026-02
2,2026-02-20 10:36:18,2026-02-20 10:37:12,1,100,54,1,2026-02-20 10:37:13,R_uwenAe3JCMbC4Jr,1.0,1.0,...,NaN,NaN,NaN,error,executionFailed,NaN,NaN,Promoter,0.9,2026-02
3,2026-02-20 15:23:16,2026-02-20 15:23:37,1,100,20,1,2026-02-20 15:23:37,R_Z3G1z9llQ1N27kZ,1.0,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,0.3,2026-02
4,2026-02-21 18:22:30,2026-02-21 18:27:53,0,100,323,1,2026-02-21 18:27:54,R_302HS4wW0igckhj,1.0,1.0,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,Detractor,5.4,2026-02
5,2026-02-26 11:12:00,2026-02-26 11:13:21,0,100,81,1,2026-02-26 11:13:22,R_3iniMJjbOE5Ho6d,1.0,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,1.4,2026-02
6,2026-02-26 12:07:25,2026-02-26 12:19:36,0,100,731,1,2026-02-26 12:19:37,R_3sjBpPlOEN84TQB,1.0,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,12.2,2026-02
7,2026-02-27 12:19:52,2026-02-27 12:22:56,1,100,184,1,2026-02-27 12:22:56,R_3fqvlSZsEIH4oOr,2.0,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,3.1,2026-02
8,2026-02-27 13:17:10,2026-02-27 13:17:15,1,100,4,1,2026-02-27 13:17:15,R_u3MjnTmwARihde1,2.0,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,0.1,2026-02
9,2026-02-27 15:31:30,2026-02-27 15:32:25,1,100,54,1,2026-02-27 15:32:25,R_yW6d2AV8ZKtsEz7,NaN,NaN,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,NaN,0.9,2026-02
10,2026-02-28 15:30:48,2026-02-28 16:18:00,0,100,2831,1,2026-02-28 16:18:01,R_1IFA5mQVS6EomTT,1.0,3.0,...,NaN,NaN,NaN,complete,NaN,NaN,NaN,Detractor,47.2,2026-02
11,2026-03-03 12:32:18,2026-03-03 12:36:17,0,100,239,1,2026-03-03 12:36:18,R_2aVLP1p5pfI30xb,1.0,2.0,...,Jan Jimenez,1.0,1.0,complete,NaN,NaN,NaN,Passive,4.0,2026-03
12,2026-03-10 15:58:50,2026-03-10 16:04:58,0,100,368,1,2026-03-10 16:04:59,R_1mr8OsMAqHw8sKy,1.0,1.0,...,NaN,1.0,1.0,complete,NaN,NaN,NaN,Passive,6.1,2026-03
13,2026-03-11 19:37:45,2026-03-11 19:39:53,0,100,127,1,2026-03-11 19:39:54,R_2V2vDcajF6D41Sd,1.0,3.0,...,NaN,1.0,4.0,complete,NaN,NaN,NaN,Promoter,2.1,2026-03
14,2026-03-12 01:16:27,2026-03-12 01:20:01,0,100,214,1,2026-03-12 01:20:02,R_31Qt9H1kfy67uA1,1.0,4.0,...,NaN,2.0,4.0,complete,NaN,NaN,NaN,Promoter,3.6,2026-03

In [27]:
df_student.describe()

,Status,progress_pct,duration_seconds,Finished,consent,library_engagement,essential_service,health_info_confidence,course_materials_satisfaction,library_nps_group,library_nps_score,degree_program,.16,health_info_confidence_num,course_materials_satisfaction_num,duration_minutes
count,15.000000,15.0,15.000000,15.0,14.000000,8.00000,8.000000,8.000000,8.000000,8.000000,8.00000,4.00,4.000000,0.0,0.0,15.000000
mean,0.466667,100.0,353.666667,1.0,1.214286,2.37500,2.250000,3.000000,3.000000,2.250000,8.12500,1.25,2.500000,NaN,NaN,5.900000
std,0.516398,0.0,711.305507,0.0,0.425815,1.30247,1.035098,1.511858,1.414214,0.886405,2.10017,0.50,1.732051,NaN,NaN,11.859294
min,0.000000,100.0,3.000000,1.0,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,5.00000,1.00,1.000000,NaN,NaN,0.000000
25%,0.000000,100.0,54.000000,1.0,1.000000,1.00000,1.750000,1.750000,2.500000,1.750000,7.25000,1.00,1.000000,NaN,NaN,0.900000
50%,0.000000,100.0,127.000000,1.0,1.000000,2.50000,2.000000,3.500000,3.000000,2.500000,8.50000,1.00,2.500000,NaN,NaN,2.100000
75%,1.000000,100.0,281.000000,1.0,1.000000,3.25000,3.000000,4.000000,4.000000,3.000000,10.00000,1.25,4.000000,NaN,NaN,4.700000
max,1.000000,100.0,2831.000000,1.0,2.000000,4.00000,4.000000,5.000000,5.000000,3.000000,10.00000,2.00,4.000000,NaN,NaN,47.200000

In [18]:
display(df_admin_quant)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,data_support_effectiveness_num,dashboard_use_nps_score,dashboard_use_nps_group,dashboard_use_nps_group_calc
0,R_7NB8iQGMqpurpEl,2026-02-20 16:22:33,2026-02,0.1,100,NaN,NaN,NaN,NaN
1,R_2CVYEiXuSLK5ukN,2026-02-21 18:51:39,2026-02,1.3,100,NaN,5.0,1.0,Detractor
2,R_2SuGE4XCiznIu2E,2026-02-26 11:11:46,2026-02,3.8,100,NaN,NaN,NaN,NaN
3,R_3GDhA9IlNZ6S9kd,2026-02-26 15:07:31,2026-02,120.0,100,NaN,NaN,NaN,NaN
4,R_1IWXwAYrqdyfCLg,2026-02-27 14:34:31,2026-02,0.1,100,NaN,NaN,NaN,NaN
5,R_7OMeQdljrxdRfRT,2026-02-27 15:32:40,2026-02,1.8,100,NaN,NaN,NaN,NaN
6,R_22mNPR1kkhssF69,2026-02-28 19:21:12,2026-02,72.3,100,NaN,NaN,NaN,NaN
7,R_22AdjyFrQIsnyMs,2026-03-01 20:15:58,2026-03,17.5,100,NaN,10.0,3.0,Promoter
8,R_1kSUbuAohDJ1LHf,2026-03-03 13:26:29,2026-03,7.6,100,NaN,6.0,1.0,Detractor
9,R_3Gd0CVhnhPT4Qnp,2026-03-06 17:42:56,2026-03,3.8,100,NaN,4.0,1.0,Detractor
10,R_2zO6jSbNXDjZntx,2026-03-09 09:08:39,2026-03,1.3,100,NaN,0.0,1.0,Detractor

In [19]:
display(df_faculty_quant)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,library_partner_nps_score,library_partner_nps_group,library_partner_nps_group_calc,degree_program,status_or_role
0,R_5lGkqSzjL3CkH9c,2026-02-20 15:17:52,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,R_5G9UYPMekeOE28r,2026-02-20 15:31:45,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R_5ew54xzON4DfJLQ,2026-02-20 15:34:05,2026-02,0.6,100,NaN,NaN,NaN,NaN,10.0,3.0,Promoter,1.0,4.0
3,R_7phTOharDJGIM3A,2026-02-21 18:45:49,2026-02,6.7,100,NaN,NaN,NaN,NaN,5.0,1.0,Detractor,NaN,NaN
4,R_3D7jElyEi0f50hH,2026-02-26 11:15:34,2026-02,2.0,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_6LU4Iu4T8Rq6bEV,2026-02-26 12:52:38,2026-02,25.0,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,R_5RggZEy7HtEWukM,2026-02-28 17:59:49,2026-02,74.6,100,NaN,NaN,NaN,NaN,5.0,1.0,Detractor,NaN,NaN
7,R_69oeSM7dkgy6b9v,2026-03-01 09:10:52,2026-03,6.2,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,4.0,1.0
8,R_637Qbsb0u5g17xV,2026-03-01 22:05:46,2026-03,4.1,100,NaN,NaN,NaN,NaN,10.0,3.0,Promoter,1.0,1.0
9,R_7Igb9R23L5Ie9Ct,2026-03-03 09:58:47,2026-03,4.5,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,2.0,1.0
10,R_52ScowzZCJnGDvO,2026-03-06 17:57:36,2026-03,98.3,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,4.0,1.0

In [20]:
display(df_student_quant)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,health_info_confidence_num,course_materials_satisfaction_num,library_nps_score,library_nps_group,library_nps_group_calc,degree_program
0,R_2Bs8DO1qWsQr8XE,2026-02-20 10:32:20,2026-02,1.2,100,NaN,NaN,10.0,3.0,Promoter,NaN
1,R_2fwDNWPIGlKfGJI,2026-02-20 10:36:14,2026-02,0.0,100,NaN,NaN,NaN,NaN,NaN,NaN
2,R_uwenAe3JCMbC4Jr,2026-02-20 10:37:13,2026-02,0.9,100,NaN,NaN,10.0,3.0,Promoter,NaN
3,R_Z3G1z9llQ1N27kZ,2026-02-20 15:23:37,2026-02,0.3,100,NaN,NaN,NaN,NaN,NaN,NaN
4,R_302HS4wW0igckhj,2026-02-21 18:27:54,2026-02,5.4,100,NaN,NaN,5.0,1.0,Detractor,NaN
5,R_3iniMJjbOE5Ho6d,2026-02-26 11:13:22,2026-02,1.4,100,NaN,NaN,NaN,NaN,NaN,NaN
6,R_3sjBpPlOEN84TQB,2026-02-26 12:19:37,2026-02,12.2,100,NaN,NaN,NaN,NaN,NaN,NaN
7,R_3fqvlSZsEIH4oOr,2026-02-27 12:22:56,2026-02,3.1,100,NaN,NaN,NaN,NaN,NaN,NaN
8,R_u3MjnTmwARihde1,2026-02-27 13:17:15,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN
9,R_yW6d2AV8ZKtsEz7,2026-02-27 15:32:25,2026-02,0.9,100,NaN,NaN,NaN,NaN,NaN,NaN
10,R_1IFA5mQVS6EomTT,2026-02-28 16:18:01,2026-02,47.2,100,NaN,NaN,5.0,1.0,Detractor,NaN
11,R_2aVLP1p5pfI30xb,2026-03-03 12:36:18,2026-03,4.0,100,NaN,NaN,8.0,2.0,Passive,1.0
12,R_1mr8OsMAqHw8sKy,2026-03-10 16:04:59,2026-03,6.1,100,NaN,NaN,8.0,2.0,Passive,1.0
13,R_2V2vDcajF6D41Sd,2026-03-11 19:39:54,2026-03,2.1,100,NaN,NaN,9.0,3.0,Promoter,1.0
14,R_31Qt9H1kfy67uA1,2026-03-12 01:20:02,2026-03,3.6,100,NaN,NaN,10.0,3.0,Promoter,2.0

In [21]:
df_admin_quant.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   response_id                     11 non-null     str
 1   recorded_date                   11 non-null     str
 2   survey_month                    11 non-null     str
 3   duration_minutes                11 non-null     float64
 4   progress_pct                    11 non-null     int64
 5   data_support_effectiveness_num  0 non-null      float64
 6   dashboard_use_nps_score         5 non-null      float64
 7   dashboard_use_nps_group         5 non-null      float64
 8   dashboard_use_nps_group_calc    5 non-null      str
dtypes: float64(4), int64(1), str(4)
memory usage: 1.4 KB

In [22]:
df_faculty_quant.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   response_id                          11 non-null     str
 1   recorded_date                        11 non-null     str
 2   survey_month                         11 non-null     str
 3   duration_minutes                     11 non-null     float64
 4   progress_pct                         11 non-null     int64
 5   collection_support_rating_num        0 non-null      float64
 6   course_materials_satisfaction_num    0 non-null      float64
 7   book_librarian_likelihood_num        0 non-null      float64
 8   research_materials_satisfaction_num  0 non-null      float64
 9   library_partner_nps_score            7 non-null      float64
 10  library_partner_nps_group            7 non-null      float64
 11  library_partner_nps_group_calc       7 non-null      str
 12  degree_program                       5 non-null      float64
 13  status_or_role                       5 non-null      float64
dtypes: float64(9), int64(1), str(4)
memory usage: 1.9 KB

In [23]:
df_student_quant.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   response_id                        15 non-null     str
 1   recorded_date                      15 non-null     str
 2   survey_month                       15 non-null     str
 3   duration_minutes                   15 non-null     float64
 4   progress_pct                       15 non-null     int64
 5   health_info_confidence_num         0 non-null      float64
 6   course_materials_satisfaction_num  0 non-null      float64
 7   library_nps_score                  8 non-null      float64
 8   library_nps_group                  8 non-null      float64
 9   library_nps_group_calc             8 non-null      str
 10  degree_program                     4 non-null      float64
dtypes: float64(6), int64(1), str(4)
memory usage: 2.1 KB

In [24]:
# get average NPS scores
df_admin_quant.describe()

,duration_minutes,progress_pct,data_support_effectiveness_num,dashboard_use_nps_score,dashboard_use_nps_group
count,11.000000,11.0,0.0,5.000000,5.000000
mean,20.872727,100.0,NaN,5.000000,1.400000
std,39.031323,0.0,NaN,3.605551,0.894427
min,0.100000,100.0,NaN,0.000000,1.000000
25%,1.300000,100.0,NaN,4.000000,1.000000
50%,3.800000,100.0,NaN,5.000000,1.000000
75%,12.550000,100.0,NaN,6.000000,1.000000
max,120.000000,100.0,NaN,10.000000,3.000000

In [25]:
df_faculty_quant.describe()

,duration_minutes,progress_pct,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,library_partner_nps_score,library_partner_nps_group,degree_program,status_or_role
count,11.000000,11.0,0.0,0.0,0.0,0.0,7.000000,7.000000,5.000000,5.000000
mean,20.200000,100.0,NaN,NaN,NaN,NaN,6.857143,1.571429,2.400000,1.600000
std,33.895988,0.0,NaN,NaN,NaN,NaN,2.193063,0.975900,1.516575,1.341641
min,0.100000,100.0,NaN,NaN,NaN,NaN,5.000000,1.000000,1.000000,1.000000
25%,1.300000,100.0,NaN,NaN,NaN,NaN,5.500000,1.000000,1.000000,1.000000
50%,4.500000,100.0,NaN,NaN,NaN,NaN,6.000000,1.000000,2.000000,1.000000
75%,15.850000,100.0,NaN,NaN,NaN,NaN,8.000000,2.000000,4.000000,1.000000
max,98.300000,100.0,NaN,NaN,NaN,NaN,10.000000,3.000000,4.000000,4.000000

In [26]:
df_student_quant.describe()

,duration_minutes,progress_pct,health_info_confidence_num,course_materials_satisfaction_num,library_nps_score,library_nps_group,degree_program
count,15.000000,15.0,0.0,0.0,8.00000,8.000000,4.00
mean,5.900000,100.0,NaN,NaN,8.12500,2.250000,1.25
std,11.859294,0.0,NaN,NaN,2.10017,0.886405,0.50
min,0.000000,100.0,NaN,NaN,5.00000,1.000000,1.00
25%,0.900000,100.0,NaN,NaN,7.25000,1.750000,1.00
50%,2.100000,100.0,NaN,NaN,8.50000,2.500000,1.00
75%,4.700000,100.0,NaN,NaN,10.00000,3.000000,1.25
max,47.200000,100.0,NaN,NaN,10.00000,3.000000,2.00

## Average NPS score by respondant group

In [44]:
NPS_scores = {'group':['Students','Faculty','Admin'], 'scores':[8.12500,6.857143,5.000000]}
NPS_scores_df = pd.DataFrame.from_dict(NPS_scores)

In [45]:
display(NPS_scores_df)

      group    scores
0  Students  8.125000
1   Faculty  6.857143
2     Admin  5.000000

In [32]:
PACIFIC_BLUE    = "#1b3764"
FOREST_GREEN    = "#366732"
VINEYARD_GREEN  = "#659a41"
NEW_LEAF        = "#99ca3c"
CLOUD_BLUE      = "#72c7f0"
SILVER_GRAY     = "#a4a9ad"
BALANCE_GRAY    = "#616467"
WARNING_RED     = "#c0392b"

In [90]:
# create barplot (vertical)
labels = {'group':'Respondent Group','scores':'NPS Score (0-10)'}
fig = px.bar(NPS_scores_df, x='group', y='scores', labels=labels, title='Average NPS Score by Respondent Group', color = 'group', color_discrete_map={
    'Students':FOREST_GREEN,
    'Faculty':VINEYARD_GREEN,
    'Admin':PACIFIC_BLUE
})
fig.add_hline(y=7, line_dash='dash', annotation_text="Passive threshold (7) ",
              annotation_position="top right")
fig.show()

# add passive threshold bar

In [50]:
def load_admin_quant_data() -> pd.DataFrame:
    df = pd.read_csv('../dashboard/data/library_impact_surveys/clean/admin_quant.csv')
    return df

In [52]:
test1 = load_admin_quant_data()

In [53]:
display(test1)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,data_support_effectiveness_num,dashboard_use_nps_score,dashboard_use_nps_group,dashboard_use_nps_group_calc
0,R_7NB8iQGMqpurpEl,2026-02-20 16:22:33,2026-02,0.1,100,NaN,NaN,NaN,NaN
1,R_2CVYEiXuSLK5ukN,2026-02-21 18:51:39,2026-02,1.3,100,NaN,5.0,1.0,Detractor
2,R_2SuGE4XCiznIu2E,2026-02-26 11:11:46,2026-02,3.8,100,NaN,NaN,NaN,NaN
3,R_3GDhA9IlNZ6S9kd,2026-02-26 15:07:31,2026-02,120.0,100,NaN,NaN,NaN,NaN
4,R_1IWXwAYrqdyfCLg,2026-02-27 14:34:31,2026-02,0.1,100,NaN,NaN,NaN,NaN
5,R_7OMeQdljrxdRfRT,2026-02-27 15:32:40,2026-02,1.8,100,NaN,NaN,NaN,NaN
6,R_22mNPR1kkhssF69,2026-02-28 19:21:12,2026-02,72.3,100,NaN,NaN,NaN,NaN
7,R_22AdjyFrQIsnyMs,2026-03-01 20:15:58,2026-03,17.5,100,NaN,10.0,3.0,Promoter
8,R_1kSUbuAohDJ1LHf,2026-03-03 13:26:29,2026-03,7.6,100,NaN,6.0,1.0,Detractor
9,R_3Gd0CVhnhPT4Qnp,2026-03-06 17:42:56,2026-03,3.8,100,NaN,4.0,1.0,Detractor
10,R_2zO6jSbNXDjZntx,2026-03-09 09:08:39,2026-03,1.3,100,NaN,0.0,1.0,Detractor

In [51]:
def load_faculty_quant_data() -> pd.DataFrame:
    df = pd.read_csv('../dashboard/data/library_impact_surveys/clean/faculty_quant.csv')
    return df

In [54]:
test2 = load_faculty_quant_data()
display(test2)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,library_partner_nps_score,library_partner_nps_group,library_partner_nps_group_calc,degree_program,status_or_role
0,R_5lGkqSzjL3CkH9c,2026-02-20 15:17:52,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,R_5G9UYPMekeOE28r,2026-02-20 15:31:45,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R_5ew54xzON4DfJLQ,2026-02-20 15:34:05,2026-02,0.6,100,NaN,NaN,NaN,NaN,10.0,3.0,Promoter,1.0,4.0
3,R_7phTOharDJGIM3A,2026-02-21 18:45:49,2026-02,6.7,100,NaN,NaN,NaN,NaN,5.0,1.0,Detractor,NaN,NaN
4,R_3D7jElyEi0f50hH,2026-02-26 11:15:34,2026-02,2.0,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_6LU4Iu4T8Rq6bEV,2026-02-26 12:52:38,2026-02,25.0,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,R_5RggZEy7HtEWukM,2026-02-28 17:59:49,2026-02,74.6,100,NaN,NaN,NaN,NaN,5.0,1.0,Detractor,NaN,NaN
7,R_69oeSM7dkgy6b9v,2026-03-01 09:10:52,2026-03,6.2,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,4.0,1.0
8,R_637Qbsb0u5g17xV,2026-03-01 22:05:46,2026-03,4.1,100,NaN,NaN,NaN,NaN,10.0,3.0,Promoter,1.0,1.0
9,R_7Igb9R23L5Ie9Ct,2026-03-03 09:58:47,2026-03,4.5,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,2.0,1.0
10,R_52ScowzZCJnGDvO,2026-03-06 17:57:36,2026-03,98.3,100,NaN,NaN,NaN,NaN,6.0,1.0,Detractor,4.0,1.0

In [49]:
def load_student_quant_data() -> pd.DataFrame:
    df = pd.read_csv('../dashboard/data/library_impact_surveys/clean/student_quant.csv')
    return df

In [55]:
test3 = load_student_quant_data()
display(test3)

,response_id,recorded_date,survey_month,duration_minutes,progress_pct,health_info_confidence_num,course_materials_satisfaction_num,library_nps_score,library_nps_group,library_nps_group_calc,degree_program
0,R_2Bs8DO1qWsQr8XE,2026-02-20 10:32:20,2026-02,1.2,100,NaN,NaN,10.0,3.0,Promoter,NaN
1,R_2fwDNWPIGlKfGJI,2026-02-20 10:36:14,2026-02,0.0,100,NaN,NaN,NaN,NaN,NaN,NaN
2,R_uwenAe3JCMbC4Jr,2026-02-20 10:37:13,2026-02,0.9,100,NaN,NaN,10.0,3.0,Promoter,NaN
3,R_Z3G1z9llQ1N27kZ,2026-02-20 15:23:37,2026-02,0.3,100,NaN,NaN,NaN,NaN,NaN,NaN
4,R_302HS4wW0igckhj,2026-02-21 18:27:54,2026-02,5.4,100,NaN,NaN,5.0,1.0,Detractor,NaN
5,R_3iniMJjbOE5Ho6d,2026-02-26 11:13:22,2026-02,1.4,100,NaN,NaN,NaN,NaN,NaN,NaN
6,R_3sjBpPlOEN84TQB,2026-02-26 12:19:37,2026-02,12.2,100,NaN,NaN,NaN,NaN,NaN,NaN
7,R_3fqvlSZsEIH4oOr,2026-02-27 12:22:56,2026-02,3.1,100,NaN,NaN,NaN,NaN,NaN,NaN
8,R_u3MjnTmwARihde1,2026-02-27 13:17:15,2026-02,0.1,100,NaN,NaN,NaN,NaN,NaN,NaN
9,R_yW6d2AV8ZKtsEz7,2026-02-27 15:32:25,2026-02,0.9,100,NaN,NaN,NaN,NaN,NaN,NaN
10,R_1IFA5mQVS6EomTT,2026-02-28 16:18:01,2026-02,47.2,100,NaN,NaN,5.0,1.0,Detractor,NaN
11,R_2aVLP1p5pfI30xb,2026-03-03 12:36:18,2026-03,4.0,100,NaN,NaN,8.0,2.0,Passive,1.0
12,R_1mr8OsMAqHw8sKy,2026-03-10 16:04:59,2026-03,6.1,100,NaN,NaN,8.0,2.0,Passive,1.0
13,R_2V2vDcajF6D41Sd,2026-03-11 19:39:54,2026-03,2.1,100,NaN,NaN,9.0,3.0,Promoter,1.0
14,R_31Qt9H1kfy67uA1,2026-03-12 01:20:02,2026-03,3.6,100,NaN,NaN,10.0,3.0,Promoter,2.0

In [56]:
df_admin_quant['dashboard_use_nps_score'].mean()

np.float64(5.0)

In [57]:
def get_NPS_scores(df_quant_admin, df_quant_faculty, df_quant_student) -> pd.DataFrame:
    avg_NPS_admin = df_quant_admin['dashboard_use_nps_score'].mean()
    avg_NPS_faculty = df_quant_faculty['library_partner_nps_score'].mean()
    avg_NPS_student = df_quant_student['library_nps_score'].mean()
    NPS_scores = {'group':['Students','Faculty','Admin'], 'scores':[avg_NPS_student,avg_NPS_faculty,avg_NPS_admin]}
    df = pd.DataFrame.from_dict(NPS_scores)
    return df

In [59]:
get_NPS_scores(df_admin_quant, df_faculty_quant, df_student_quant)

      group    scores
0  Students  8.125000
1   Faculty  6.857143
2     Admin  5.000000

In [ ]:
def plot_avg_NPS(df: pd.DataFrame) -> None:
    """
    Bar chart plotting the average Net Promoter Score for each of the three Impact Survey respondent groups (Students, Faculty, and Admin).
    """
    if df.empty:
        st.info("No appointment data available.")
        return

    data = NPS_scores_df

    labels = {'group':'Respondent Group','scores':'NPS Score (0-10)'}
    fig = px.bar(NPS_scores_df, x='group', y='scores', labels=labels, title='Average NPS Score by Respondent Group', color = 'group', color_discrete_map={
    'Students':FOREST_GREEN,
    'Faculty':VINEYARD_GREEN,
    'Admin':PACIFIC_BLUE
    })
    fig.add_hline(y=7, line_dash='dash', annotation_text="Passive threshold (7) ",
              annotation_position="top right")

    st.plotly_chart(fig, use_container_width=True)

## Satisfaction ratings across all groups

In [64]:
df_student_quant['health_info_confidence_num'].dropna(inplace=True)

In [80]:
df_student['health_info_confidence'].dropna().mean()

np.float64(3.0)

In [71]:
health_info_confidence = df_student['health_info_confidence'].dropna().mean()
print(health_info_confidence)

3.0

In [72]:
data_support_effectiveness = df_admin['data_support_effectiveness'].dropna().mean()
print(data_support_effectiveness)

3.3333333333333335

In [75]:
df_faculty.describe()

,Status,progress_pct,duration_seconds,Finished,consent,collection_support_rating,course_materials_satisfaction,book_librarian_likelihood,research_materials_satisfaction,ill_or_copyright_experience,library_partner_nps_group,library_partner_nps_score,degree_program,status_or_role,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,duration_minutes
count,11.000000,11.0,11.000000,11.0,11.000000,7.000000,7.000000,7.000000,7.000000,4.00000,7.000000,7.000000,5.000000,5.000000,0.0,0.0,0.0,0.0,11.000000
mean,0.272727,100.0,1212.545455,1.0,1.181818,2.714286,3.142857,3.714286,3.714286,4.50000,1.571429,6.857143,2.400000,1.600000,NaN,NaN,NaN,NaN,20.200000
std,0.467099,0.0,2034.297587,0.0,0.404520,0.755929,0.690066,0.755929,0.755929,0.57735,0.975900,2.193063,1.516575,1.341641,NaN,NaN,NaN,NaN,33.895988
min,0.000000,100.0,4.000000,1.0,1.000000,2.000000,2.000000,3.000000,3.000000,4.00000,1.000000,5.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,0.100000
25%,0.000000,100.0,80.500000,1.0,1.000000,2.000000,3.000000,3.000000,3.000000,4.00000,1.000000,5.500000,1.000000,1.000000,NaN,NaN,NaN,NaN,1.300000
50%,0.000000,100.0,271.000000,1.0,1.000000,3.000000,3.000000,4.000000,4.000000,4.50000,1.000000,6.000000,2.000000,1.000000,NaN,NaN,NaN,NaN,4.500000
75%,0.500000,100.0,951.500000,1.0,1.000000,3.000000,3.500000,4.000000,4.000000,5.00000,2.000000,8.000000,4.000000,1.000000,NaN,NaN,NaN,NaN,15.850000
max,1.000000,100.0,5900.000000,1.0,2.000000,4.000000,4.000000,5.000000,5.000000,5.00000,3.000000,10.000000,4.000000,4.000000,NaN,NaN,NaN,NaN,98.300000

In [79]:
df_faculty_quant.describe()

,duration_minutes,progress_pct,collection_support_rating_num,course_materials_satisfaction_num,book_librarian_likelihood_num,research_materials_satisfaction_num,library_partner_nps_score,library_partner_nps_group,degree_program,status_or_role
count,11.000000,11.0,0.0,0.0,0.0,0.0,7.000000,7.000000,5.000000,5.000000
mean,20.200000,100.0,NaN,NaN,NaN,NaN,6.857143,1.571429,2.400000,1.600000
std,33.895988,0.0,NaN,NaN,NaN,NaN,2.193063,0.975900,1.516575,1.341641
min,0.100000,100.0,NaN,NaN,NaN,NaN,5.000000,1.000000,1.000000,1.000000
25%,1.300000,100.0,NaN,NaN,NaN,NaN,5.500000,1.000000,1.000000,1.000000
50%,4.500000,100.0,NaN,NaN,NaN,NaN,6.000000,1.000000,2.000000,1.000000
75%,15.850000,100.0,NaN,NaN,NaN,NaN,8.000000,2.000000,4.000000,1.000000
max,98.300000,100.0,NaN,NaN,NaN,NaN,10.000000,3.000000,4.000000,4.000000

In [78]:
collection_support = df_faculty['collection_support_rating'].dropna().mean()
print(collection_support)

research_materials_satisfaction = df_faculty['research_materials_satisfaction'].dropna().mean()
print(research_materials_satisfaction)

course_materials_satisfaction = df_faculty['course_materials_satisfaction'].dropna().mean()
print(course_materials_satisfaction)

2.7142857142857144
3.7142857142857144
3.142857142857143

In [81]:
def get_impact_satisfaction_ratings(df_admin, df_faculty, df_student) -> pd.DataFrame:
    data_support_effectiveness = df_admin['data_support_effectiveness'].dropna().mean()
    health_info_confidence = df_student['health_info_confidence'].dropna().mean()
    collection_support = df_faculty['collection_support_rating'].dropna().mean()
    research_materials_satisfaction = df_faculty['research_materials_satisfaction'].dropna().mean()
    course_materials_satisfaction = df_faculty['course_materials_satisfaction'].dropna().mean()
    satisfaction_ratings = {'rating':['Data Support Effectiveness','Health Info Confidence','Collection Support', 'Research Materials Satisfaction', 'Course Materials Satisfaction'], 'scores':[data_support_effectiveness,health_info_confidence,collection_support, research_materials_satisfaction, course_materials_satisfaction]}
    satisfaction_ratings_df = pd.DataFrame.from_dict(satisfaction_ratings)
    return satisfaction_ratings_df

In [83]:
satisfaction_ratings_df = get_impact_satisfaction_ratings(df_admin, df_faculty, df_student)

In [94]:
satisfaction_ratings_df.head()

                            rating    scores
0       Data Support Effectiveness  3.333333
1           Health Info Confidence  3.000000
2               Collection Support  2.714286
3  Research Materials Satisfaction  3.714286
4    Course Materials Satisfaction  3.142857

In [95]:
labels = {'rating':'Rating','scores':'Mean Score (1-5)'}
fig1 = px.bar(satisfaction_ratings_df, x='scores', y='rating', labels=labels, title='Satisfaction Ratings Across All Groups', color = 'rating', color_discrete_map={'Data Support Effectiveness':CLOUD_BLUE, 'Health Info Confidence':NEW_LEAF, 'Collection Support':VINEYARD_GREEN, 'Research Materials Satisfaction':FOREST_GREEN, 'Course Materials Satisfaction':PACIFIC_BLUE})

fig1.show()

In [ ]:
def plot_impact_satisfaction_ratings(df):
    """
    Horizontal bar chart plotting key satisfaction ratings across the three Imapct Survey respondent groups (Students, Faculty, and Admin).
    """
    if df.empty:
        st.info("No appointment data available.")
        return

    labels = {'rating':'Rating','scores':'Mean Score (1-5)'}
    fig = px.bar(df, x='scores', y='rating', labels=labels, title='Satisfaction Ratings Across All Groups', color = 'rating', color_discrete_map={
    'Data Support Effectiveness':CLOUD_BLUE,
    'Health Info Confidence':NEW_LEAF,
    'Collection Support':VINEYARD_GREEN,
    'Research Materials Satisfaction':FOREST_GREEN,
    'Course Materials Satisfaction':PACIFIC_BLUE
    })

    st.plotly_chart(fig, use_container_width=True)